"""Tests for the package-level report gate (validate_okn_report).

The skill mandates an exact deliverable folder — a fixed top-level file set, flat machine-extract data/,
no anti-pattern builders or scratch/QA artifacts, a workbook with named sheets, and a section order that
ends Reproducibility → References. This is the automated gate that enforces all of that at once; here we
build a minimal COMPLIANT package (which must PASS) and then inject one violation at a time, asserting
each is caught."""

import re
import sys
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

# validate_okn_report is a report-style skill script (stdlib-only), not part of the mcp_okn package.
sys.path.insert(
    0, str(Path(__file__).resolve().parent.parent / "skills/okn-report-style/scripts")
)
import validate_okn_report as v

TOKEN = "Demo"

# A minimal report whose ## sections satisfy the order rules: Sources present, and the last two sections
# are Reproducibility then References.
_REPORT_MD = """# Demo study

**Date:** 2026-07-25 · **Endpoint:** OKN federated SPARQL · **Model:** claude-opus-5

> Unit of analysis: demo. Coverage: demo. Abbreviations: n/a.

## Executive summary

The headline result is a demonstration with enough prose to clear the parity word-ratio floor easily.

## Sources used

One row per knowledge graph actually queried in this demonstration package for the parity gate.

## Comparison with prior work

Concordance of each demonstration claim against the imaginary prior literature for this fixture.

## Full ranked results

<!-- RESULTS_TABLE -->

![Figure 1](figures/fig1_demo.png)

> ***Figure 1. A demonstration panel showing nothing in particular for the fixture package.***

## Summary of findings & limitations

A recap of the demonstration findings followed by the usual caveats for a fixture of this kind.

## Reproducibility

See Demo_reproducibility.md for the spec and verbatim queries backing this demonstration package.

## References

1. Demo Author, et al. A demonstration. *Demo Journal*. 2026.
"""


# The reproducibility record as create_reproducibility_record writes it: a provenance header (Skills
# included) above the spec and the verbatim queries.
_REPRO_MD = """# Demo Reproducibility Record

- **Date:** 2026-07-25
- **Model:** claude-opus-5
- **Generated by:** mcp-okn v0.1.0
- **Skills:** okn-bioanalysis v0.1.1 · okn-report-style v0.1.2
- **Contents:** no queries or diagrams

## Knowledge graphs used

- `sawgraph` — <https://purl.org/okn/frink/kg/sawgraph>

## SPARQL queries

_No queries logged._
"""


def _repro_with_skills(study: Path, line: str | None) -> None:
    """Rewrite the fixture record's `- **Skills:**` header line (None removes it)."""
    lines = [ln for ln in _REPRO_MD.splitlines() if not ln.startswith("- **Skills:**")]
    if line is not None:
        lines.insert(lines.index("- **Contents:** no queries or diagrams"), line)
    (study / f"{TOKEN}_reproducibility.md").write_text("\n".join(lines) + "\n")


def _md_to_html(md: str) -> str:
    """A trivial, parity-passing render: strip Markdown markup and wrap each line in <p> inside ONE
    well-formed document, so every heading text is present and the visible word count matches the .md."""
    body = []
    for line in md.splitlines():
        s = re.sub(r"^[#>\s]+", "", line).replace("*", "").strip()
        if s:
            body.append(f"<p>{escape(s)}</p>")
    return (
        "<!DOCTYPE html><html><head><title>Demo</title></head><body>\n"
        + "\n".join(body)
        + "\n</body></html>"
    )


def _write_xlsx(
    path: Path, sheets=("Ranked Results", "Methods & Rules"), abbrev=True
) -> None:
    """A minimal xlsx (a zip) carrying just what the validator reads: sheet names in xl/workbook.xml and,
    optionally, the word 'Abbreviations' as an inline cell string."""
    sheets_xml = "".join(
        f'<sheet name="{escape(n)}" sheetId="{i + 1}" r:id="rId{i + 1}"/>'
        for i, n in enumerate(sheets)
    )
    workbook = (
        '<?xml version="1.0"?><workbook '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        f"<sheets>{sheets_xml}</sheets></workbook>"
    )
    cell = (
        '<row><c t="inlineStr"><is><t>Abbreviations</t></is></c></row>'
        if abbrev
        else ""
    )
    ws = f"<worksheet><sheetData>{cell}</sheetData></worksheet>"
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("xl/workbook.xml", workbook)
        z.writestr("xl/worksheets/sheet1.xml", ws)


def _build(tmp_path: Path) -> Path:
    """Create a fully compliant Demo/ package under tmp_path and return its path."""
    study = tmp_path / TOKEN
    (study / "figures").mkdir(parents=True)
    (study / "data").mkdir()
    (study / "scripts").mkdir()

    (study / f"{TOKEN}_report.md").write_text(_REPORT_MD)
    (study / f"{TOKEN}_report.html").write_text(_md_to_html(_REPORT_MD))
    (study / f"{TOKEN}_literature_comparison.md").write_text(
        "# Lit comparison\n\n1. Demo. 2026.\n"
    )
    # No ```sparql blocks → the diagram gate passes trivially (nothing to diagram). The header mirrors
    # what create_reproducibility_record emits, including the Skills provenance line.
    (study / f"{TOKEN}_reproducibility.md").write_text(_REPRO_MD)
    _write_xlsx(study / f"{TOKEN}_results.xlsx")

    (study / "figures" / "fig1_demo.png").write_bytes(b"\x89PNG\r\n")
    (study / "data" / "ranked.csv").write_text("id,score\n1,0.9\n")
    (study / "scripts" / "make_figures.py").write_text("# demo\n")
    return study


def test_valid_package_passes(tmp_path):
    study = _build(tmp_path)
    r = v.validate(str(study))
    assert r.errors == [], r.errors
    assert v.main([str(study)]) == 0


def test_missing_literature_comparison_passes(tmp_path):
    # The companion is OPTIONAL — absent when §8 (Comparison with prior work) wasn't done.
    study = _build(tmp_path)
    (study / f"{TOKEN}_literature_comparison.md").unlink()
    r = v.validate(str(study))
    assert r.errors == [], r.errors


def test_unexpected_toplevel_file_fails(tmp_path):
    study = _build(tmp_path)
    (study / "notes.txt").write_text("stray")
    r = v.validate(str(study))
    assert any("unexpected top-level" in e for e in r.errors)
    assert v.main([str(study)]) == 1


def test_missing_required_file_fails(tmp_path):
    study = _build(tmp_path)
    (study / f"{TOKEN}_results.xlsx").unlink()
    r = v.validate(str(study))
    assert any("missing required file" in e for e in r.errors)


def test_data_reproducibility_intermediates_pass(tmp_path):
    # Diagram cache, mermaid/ sources, the {{key}} template, and subset extracts are legitimate
    # reproducibility intermediates (SANS keeps them) — they must NOT be errors.
    study = _build(tmp_path)
    (study / "data" / "diagrams.json").write_text("[]")
    (study / "data" / "mermaid").mkdir()
    (study / "data" / "mermaid" / "1.mmd").write_text("graph TD;")
    (study / "data" / "report_template.md").write_text("# {{title}}\n")
    (study / "data" / "de_ocular_small.csv").write_text("id\n1\n")
    r = v.validate(str(study))
    assert r.errors == [], r.errors


def test_data_literature_comparison_misplaced_fails(tmp_path):
    # The one thing the skill explicitly bars from data/: the literature comparison (a top-level sibling).
    study = _build(tmp_path)
    (study / "data" / f"{TOKEN}_literature_comparison.md").write_text("# stray\n")
    r = v.validate(str(study))
    assert any("literature comparison" in e for e in r.errors)


def test_scripts_antipattern_builder_fails(tmp_path):
    # The anti-pattern is BEHAVIORAL: it writes the report .html without the renderer.
    study = _build(tmp_path)
    (study / "scripts" / "make_html.py").write_text(
        "body = ['<h1>highlights</h1>']\n"
        "open('Demo_report.html', 'w').write('<html>' + ''.join(body) + '</html>')\n"
    )
    r = v.validate(str(study))
    assert any("anti-pattern" in e for e in r.errors)


def test_renderer_driver_named_build_html_passes(tmp_path):
    # A thin per-study driver that CALLS build_report_from_markdown is correct even named build_html.py
    # (this is exactly SANS/scripts/build_html.py) — it must NOT be flagged.
    study = _build(tmp_path)
    (study / "scripts" / "build_html.py").write_text(
        "from build_report_html import build_report_from_markdown, candidate_table\n"
        "build_report_from_markdown('Demo_report.md', 'Demo_report.html', table=None)\n"
    )
    r = v.validate(str(study))
    assert not any("anti-pattern" in e for e in r.errors), r.errors


def test_missing_workbook_sheet_fails(tmp_path):
    study = _build(tmp_path)
    _write_xlsx(
        study / f"{TOKEN}_results.xlsx", sheets=("Ranked Results",)
    )  # drop Methods & Rules
    r = v.validate(str(study))
    assert any("Methods & Rules" in e for e in r.errors)


def test_workbook_missing_abbreviations_warns(tmp_path):
    study = _build(tmp_path)
    _write_xlsx(study / f"{TOKEN}_results.xlsx", abbrev=False)
    r = v.validate(str(study))
    assert r.errors == []  # a warning, not an error
    assert any("Abbreviation" in w for w in r.warnings)


def test_section_order_references_not_last_fails(tmp_path):
    study = _build(tmp_path)
    md = _REPORT_MD + "\n## Appendix\n\nSomething after References.\n"
    (study / f"{TOKEN}_report.md").write_text(md)
    (study / f"{TOKEN}_report.html").write_text(_md_to_html(md))
    r = v.validate(str(study))
    assert any("References" in e and "last" in e for e in r.errors)


def test_reproducibility_and_references_swapped_fails(tmp_path):
    study = _build(tmp_path)
    md = _REPORT_MD.replace(
        "## Reproducibility\n\nSee Demo_reproducibility.md for the spec and verbatim queries backing this demonstration package.\n\n## References\n\n1. Demo Author, et al. A demonstration. *Demo Journal*. 2026.\n",
        "## References\n\n1. Demo Author, et al. A demonstration. *Demo Journal*. 2026.\n\n## Reproducibility\n\nSee Demo_reproducibility.md for the spec and verbatim queries.\n",
    )
    assert md != _REPORT_MD  # guard: the replace actually fired
    (study / f"{TOKEN}_report.md").write_text(md)
    (study / f"{TOKEN}_report.html").write_text(_md_to_html(md))
    r = v.validate(str(study))
    assert r.errors  # order / last-two rule violated


def test_duplicate_reproducibility_file_fails(tmp_path):
    study = _build(tmp_path)
    (study / f"{TOKEN}_transcript.md").write_text("# stray transcript\n")
    r = v.validate(str(study))
    # Caught either as a split-reproducibility error or as an unexpected top-level file — both are correct.
    assert any(
        "reproducibility" in e.lower() or "transcript" in e.lower() for e in r.errors
    )


def test_species_filenames_are_not_mistaken_for_a_spec_file(tmp_path):
    """`_spec` used to be a bare substring test, so `_species` matched it: a study with
    `wl_species_summary.csv` in `data/` failed the split-reproducibility check on a CSV.
    Data and figures can never BE a spec document, and `_spec` must end the word."""
    study = _build(tmp_path)
    (study / "data" / "wl_species_summary.csv").write_text("taxon,n\nAves,3\n")
    (study / "data" / "sentinel_species_county.csv").write_text("fips,n\n12086,4\n")
    (study / "figures" / "fig9_species_value.png").write_bytes(b"\x89PNG\r\n\x1a\n")
    # A prose file whose stem genuinely ends in `_spec` is still the anti-pattern.
    r = v.validate(str(study))
    assert not any("more than one reproducibility" in e for e in r.errors), r.errors

    (study / "data" / "extra_spec.md").write_text("# a second spec\n")
    r2 = v.validate(str(study))
    assert any("more than one reproducibility" in e for e in r2.errors)


def test_missing_skills_header_line_fails(tmp_path):
    # `skills=` is caller-supplied — the server can't see which skills a session loaded — so a record
    # with no Skills line is a forgotten argument, and the package silently claims no methodology.
    study = _build(tmp_path)
    _repro_with_skills(study, None)
    r = v.validate(str(study))
    assert any("no '- **Skills:**' line" in e for e in r.errors)
    assert v.main([str(study)]) == 1


def test_skills_line_without_report_style_fails(tmp_path):
    # This validator only runs on an okn-report-style package, so that skill was used by definition.
    study = _build(tmp_path)
    _repro_with_skills(study, "- **Skills:** okn-bioanalysis v0.1.1")
    r = v.validate(str(study))
    assert any("does not name okn-report-style" in e for e in r.errors)


def test_unversioned_skills_entry_warns_only(tmp_path):
    # Naming the skill without pinning its version still identifies the methodology — advisory, not blocking.
    study = _build(tmp_path)
    _repro_with_skills(study, "- **Skills:** okn-report-style")
    r = v.validate(str(study))
    assert r.errors == [], r.errors
    assert any("without a version" in w for w in r.warnings)


def test_skills_mentioned_outside_header_does_not_satisfy_gate(tmp_path):
    # Only the tool-generated header counts; a mention in the spec body is not provenance.
    study = _build(tmp_path)
    _repro_with_skills(study, None)
    repro = study / f"{TOKEN}_reproducibility.md"
    repro.write_text(
        repro.read_text() + "\n- **Skills:** okn-report-style v0.1.2\n",
    )
    r = v.validate(str(study))
    assert any("no '- **Skills:**' line" in e for e in r.errors)


# ── Model provenance ─────────────────────────────────────────────────────────────────────────────────
# The model id is written by three different paths (hand-authored title block → lifted into the .html by
# the renderer; `model=` into the record) and nothing reconciles them, so the gate checks all three are
# present, specific, and identical.


def _set_model(study: Path, *, md=None, html=None, repro=None) -> None:
    """Rewrite the model id in one or more artifacts (None = leave alone, "" = drop the field)."""
    for value, path, old in (
        (md, study / f"{TOKEN}_report.md", "**Model:** claude-opus-5"),
        (html, study / f"{TOKEN}_report.html", "Model: claude-opus-5"),
        (repro, study / f"{TOKEN}_reproducibility.md", "- **Model:** claude-opus-5"),
    ):
        if value is None:
            continue
        text = path.read_text()
        assert (
            old in text
        )  # guard: the fixture still carries the field we mean to rewrite
        path.write_text(
            text.replace(old, old.replace("claude-opus-5", value) if value else "")
        )


def test_missing_model_in_report_fails(tmp_path):
    study = _build(tmp_path)
    _set_model(study, md="")
    r = v.validate(str(study))
    assert any("no model recorded" in e for e in r.errors), r.errors
    assert v.main([str(study)]) == 1


def test_missing_model_in_record_fails(tmp_path):
    study = _build(tmp_path)
    _set_model(study, repro="")
    r = v.validate(str(study))
    assert any("no model recorded" in e for e in r.errors), r.errors


def test_generic_model_family_name_fails(tmp_path):
    # "Claude" reads as filled-in provenance while identifying nothing that ran.
    study = _build(tmp_path)
    _set_model(study, md="Claude", html="Claude", repro="Claude")
    r = v.validate(str(study))
    assert any("not an exact model id" in e for e in r.errors), r.errors
    assert not any("differs across the package" in e for e in r.errors)


def test_placeholder_model_fails(tmp_path):
    study = _build(tmp_path)
    _set_model(study, md="unknown", html="unknown", repro="unknown")
    r = v.validate(str(study))
    assert any("not an exact model id" in e for e in r.errors), r.errors


def test_model_mismatch_between_md_and_record_fails(tmp_path):
    study = _build(tmp_path)
    _set_model(study, repro="claude-opus-4-8")
    r = v.validate(str(study))
    assert any("differs across the package" in e for e in r.errors), r.errors


def test_model_mismatch_between_md_and_html_fails(tmp_path):
    # A hand-built .html can disagree with the .md; parity is heading/word-count based and misses it.
    study = _build(tmp_path)
    _set_model(study, html="claude-opus-4-8")
    r = v.validate(str(study))
    assert any("differs across the package" in e for e in r.errors), r.errors


def test_non_anthropic_model_id_passes(tmp_path):
    # The rule is domain-neutral: any specific vendor id is fine, only generic ones are rejected.
    study = _build(tmp_path)
    _set_model(study, md="gpt-5.6-sol", html="gpt-5.6-sol", repro="gpt-5.6-sol")
    r = v.validate(str(study))
    assert r.errors == [], r.errors


def test_model_mentioned_outside_header_does_not_satisfy_gate(tmp_path):
    # Only the provenance header counts — a `Model:` down in the spec body is not the tool-written field.
    study = _build(tmp_path)
    _set_model(study, repro="")
    repro = study / f"{TOKEN}_reproducibility.md"
    repro.write_text(repro.read_text() + "\n- **Model:** claude-opus-5\n")
    r = v.validate(str(study))
    assert any("no model recorded" in e for e in r.errors), r.errors


def test_junk_file_in_subdir_fails(tmp_path):
    study = _build(tmp_path)
    (study / "data" / "scratch.tmp").write_text("junk")
    r = v.validate(str(study))
    assert any("scratch/QA/temp" in e for e in r.errors)
