"""Which BUILD of the server is running.

``__version__`` has been ``0.1.0`` across the whole history, so it cannot tell two
deployments apart — every reproducibility record claims the same "Generated by" line
whatever code produced it. That matters because the hosted server routinely lags the
repo: a record generated against it may predate features the same version number
carries locally. The build id closes that gap, and is resolved in this order:

1. ``MCP_OKN_BUILD`` — set by the deploy. Authoritative, and the only path that works
   in a container with no git metadata.
2. ``_build.py`` (``BUILD_ID``) — written by a packaging step, if one does that.
3. ``git rev-parse --short HEAD`` — the developer case, running from a checkout.
4. ``"unknown"`` — nothing identifiable; the caller sees that rather than a guess.
"""

from __future__ import annotations

import functools
import os
import subprocess
from pathlib import Path

#: Returned when the build genuinely can't be identified — never a made-up value.
UNKNOWN = "unknown"


def _from_git() -> str:
    """Short HEAD sha when running from a checkout, else "".

    Only attempted when a `.git` exists beside the package, so a deployed container
    never pays for (or logs) a failed subprocess.
    """
    root = Path(__file__).resolve().parent.parent.parent
    if not (root / ".git").exists():
        return ""
    try:
        # Fixed argv, no shell, no user input.
        out = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return out.stdout.strip() if out.returncode == 0 else ""


@functools.lru_cache(maxsize=1)
def build_id() -> str:
    """Return the running build's identifier (see the module docstring for order)."""
    env = os.environ.get("MCP_OKN_BUILD", "").strip()
    if env:
        return env
    try:
        # Optional: only exists if a packaging step generated it.
        from ._build import BUILD_ID
    except ImportError:
        pass
    else:
        if str(BUILD_ID).strip():
            return str(BUILD_ID).strip()
    return _from_git() or UNKNOWN


def build_suffix() -> str:
    """`" (build abc1234)"` for the provenance header, or `""` when unidentifiable.

    Empty rather than "(build unknown)": a header that says nothing is honest, where
    one that says "unknown" just adds noise to every record generated from a tarball.
    """
    current = build_id()
    return "" if current == UNKNOWN else f" (build {current})"
